
#mini project backend server creation

apiVersion: v1
kind: ConfigMap
metadata:
 name: backend
 namespace: helmdemoproject-3
data:
 DB_HOST: mysqlcon

---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: nodejsbackend
 namespace: helmdemoproject-3
 labels:
   tier: backend
   environment: dev
spec:
 replicas: {{ .Values.deployment.replicas }}
 selector:
  matchLabels:
   tier: backend
   project: minipro
 template:
  metadata:
   labels:
    tier: backend
    project: minipro
  spec:
   containers:
   - name: backendcontainer
     image: joindevops/backend:{{ .Values.deployment.imageVersion }}
     resources:
      requests:
       cpu: 100m
       memory: 128Mi
      limits:
       cpu: 100m
       memory: 128Mi       
     envFrom:
     - configMapRef:
        name: {{ .Values.deployment.configmap.name }}

---

apiVersion: v1
kind: Service
metadata: 
 name: backend
 namespace: helmdemoproject-3 
spec:
 selector:
  tier: backend
  project: minipro
 ports:
 - name: mysql-port
   protocol: TCP
   port: 8080
   targetPort: 8080

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-demo
 namespace: helmdemoproject-3
spec:
 scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: nodejsbackend
 minReplicas: 2
 maxReplicas: 10
 targetCPUUtilizationPercentage: {{ .Values.horizantalpodauto.cpu }} #usually 75 in real environment
 

  
