apiVersion: v1
kind: storageClass
metadata:
 name: expense-ebs
reclaimPolicy: retain
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer  #storage will be created when pod is getting created

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: ebs-dynamic
spec: 
 storageClassName: "expense-ebs"
 accessModes:
 - ReadWriteOnce
 resources:
  requests:
   storage: 5Gi

---

apiVersion: v1
kind: Pod
metadata:
 name: ebs-dynamic
 labels:
  name: dynamostorage
spec:
 containers:
 - name: nginx
   image: nginx
   volumeMounts:
   - name: ebs-dyamnic
     mountpath: /usr/share/nginx/html
  volumes:
  - name: ebs-dyamnic
    persistentVoluneClaim:
     claimName: ebs-dynamic

---

apiVersion: v1
kind: Service
metadata: 
 name: ebs-dynamic
spec:
 type: LoadBalancer
 selector:
  name: dynamostorage
 ports:
 - name: nginx-svc-port
   protocol: TCP
   port: 80
   targetPort: 80
  
