apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  namespace: expense
spec:
 affinity:
  nodeAffinity:
  #  requiredDuringSchedulingIgnoreDuringExecution:
  #   nodeSelectorTerms:
  #   - matchExpressions:
  #     - key: hardware
  #       operator: In
  #       values: 
  #       - gpu 
   preferredDuringSchedulingIgnoreDuringExecution:
   - weight: 1
     preference:
    - matchExpressions:
      - key: another
        operator: In
        values: 
        - value 
 containers:   
 - name: nginx
   image: nginx
 tolerations:
 - key: "hardware"
   operator: "Equal"
   value: "gpu"
   effect: "NoSchedule"
