apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 name: pod-reader
 namespace: expense
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get" , "list" , "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: trainee
 namespace: expense
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: Role
 name: pod-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: Satti

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 name: expense-admin
 namespace: expense
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: tadmin
 namespace: expense
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: Role
 name: expense-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: Hari

---


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: nsadmin
 rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["nodes","persistentvolumes","namespaces"]
  verbs: ["get", "list", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: tadmin
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: Hari
