apiVersion: storage.k8.io/v1
kind: StorageClass
metadata:
 name: 3tiervol
reclaimPolicy: Retain
provisioner: ebs.csi.aws.com 
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: dbpvc
spec:
 storageClassName: 3tiervol
 accessModes:
    - ReadWriteOnce
 resources:
    requests:
      storage: 2Gi