apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-east-1

managedNodeGroups:
  - name: my-nodes
    instanceTypes: ["m5.large", "m5a.large", "t3.medium"]  # multiple types → reduces Spot failure
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    spot: true
    availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]  # multiple AZs → higher success
