apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
 name: my-cluster
 region: ap-south-1

managedNodeGroups:
 - name: my-nodes
   instanceType: t4.large
   desiredCapacity: 2
   spot: true  # must not used for Deployment environment