apiVersion: apps/v1
kind: Deployment
metadata:
 name: app1
 labels:
   name: nginx
   tier: frontend

spec:
 replicas: 3
 selector:
  matchLabels:
   name: nginx1
   tier: frontend

 template:
  metadata:
    labels:
     name: nginx1
     tier: frontend
  spec:
   containers:
    - name: nginx
      image: joindevops/app1:v1
---

apiVersion: v1
kind: Service
metadata:
 name: nginxlb
spec:
 selector:
   name: nginx1
   tier: frontend
 ports:
 - name: nginx-svc-port
   protocol: TCP
   port: 80
   targetPort: 80