apiVersion: apps/v1
kind: Deployment
metadata:
 name: mysql
 namespace: Helmdemoproject-3 
 labels:  
  project: minipro
  environment: dev
spec:
 replicas: {{ .Values.deployment.replicas }}
 selector:
   matchLabels:
      tier: mysql-db
      project: minipro
 template:
   metadata:
      labels:
        tier: mysql-db
        project: minipro
   spec:
      containers:
      - name: mysql
        image: joindevops/mysql:{{ .Values.deployment.imageVersion }}
       

---

apiVersion: v1
kind: Service
metadata:
 name: mysqlcon
 namespace: helmdemoproject-3
spec:
 selector:
   tier: mysql-db
   project: minipro
 ports:
 - name: mysql-port
   protocol: TCP
   port: 3306
   targetPort: 3306


