apiVersion: apps/v1
kind: Deployment
metadata:
   name: todo
   namespace: project-k8
   labels:
    env: dev
    name: project-k8
spec:
 replicas: 2
 selector:
   matchLabels:
    project: K8
    env: dev
    tier: db
 template:
  metadata:
   labels: 
    project: K8
    env: dev
    tier: db
  spec:
   #imagePullSecrets:  #for practice used MINIKube so to pull images from our Private ECR we create a ecr-secret and passing from here to enable minikube to pull image
   #- name: ecr-secret 
   containers:
   - name: todo-db
     image: 589820790160.dkr.ecr.us-east-1.amazonaws.com/postgres:v1
     #imagePullPolicy: Never
     volumeMounts:
     - name: storage
       mountPath: /var/lib/postgresql/data
     envFrom:
      - configMapRef:
         name: dbconfig
      - secretRef:
         name: dbsecret
     ports:
     - containerPort: 5432
  volumes:
    - name: storage
      persistentVolumeClaim:
      claimName: 3tiervol

---
apiVersion: v1
kind: Service
metadata:
 name: postgres
 namespace: project-k8
spec:
 selector:
   project: K8
   env: dev
   tier: db
 ports:
 - port: 5432
   targetPort: 5432



