apiVersion: apps/v1
kind: Deployment
metadata:
 name: mysql
 namespace: smallproject-3 
 labels:  
  project: minipro
  environment: dev
spec:
 replicas: 1
 selector:
   matchlabels:
      tier: mysqldb
      project: minipro
 template:
   metadata:
      labels:
        tier: mysqldb
        project: minipro
   spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1


