
#mini project backend server creation

apiVersion: v1
kind: ConfigMap
metadata:
 name: backend
 namespace: smallproject-3
data:
 DB_HOST: mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: mysql
 namespace: smallproject-3 
 labels:  
  project: minipro
  environment: dev
spec:
 replicas: 1
 selector:
   matchLabels:
      tier: mysql-db
      project: minipro
 template:
   metadata:
      labels:
        tier: mysql-db
        project: minipro
   spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1
        envFrom:
        - configMapRef:
           name: backend

---

apiVersion: v1
kind: Service
metadata:
 name: mysqlcon
 namespace: smallproject-3
spec:
 selector:
   tier: mysql-db
   project: minipro
 ports:
 - name: mysql-port
   protocol: TCP
   port: 3306
   targetPort: 3306


